### ISSUE TITLE
Práctica 3 Fundamentos de Tópicos Avanzandos de Programación 

### ISSUE THREAD

**Issue by marxgonzalez29** [SistemasTecTlaxiaco/actividad-3-practica-de-interfaz-grafica-con-interactividad-ingestudiantes#1]
[practca2_interfasGrafica.docx](https://github.com/SistemasTecTlaxiaco/actividad-3-practica-de-interfaz-grafica-con-interactividad-ingestudiantes/files/14335159/practca2_interfasGrafica.docx)
Emmanuel Marx Salazar
Edgar Axel Sandoval Hernández

**Comment by Daisy-GonzalezLita12** [comment]
Hola buenos dias compañeros, su calificación es 17% de 20 %

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
